server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 10
    
spring:
  datasource:
    url: jdbc:mysql://123.58.34.160:3306/flight_data?useUnicode=true&characterEncoding=UTF-8
    username: flightplan
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    
    
mybatis:
  mapper-locations:
    - classpath*:/orm/*.xml

logging:
  file: HKA-Audit.log
  
